plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-miko.js
    spec: "@yarnpkg/plugin-miko"
  - path: .yarn/plugins/@yarnpkg/plugin-babel.js
    spec: "@yarnpkg/plugin-babel"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
