enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-miko.js
    spec: "@yarnpkg/plugin-miko"
  - path: .yarn/plugins/@yarnpkg/plugin-babel.js
    spec: "@yarnpkg/plugin-babel"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
