plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-miko.js
    spec: "@yarnpkg/plugin-miko"
  - path: .yarn/plugins/@yarnpkg/plugin-babel.js
    spec: "@yarnpkg/plugin-babel"
  - path: .yarn/plugins/@yarnpkg/plugin-builder.js
    spec: "@yarnpkg/plugin-builder"

yarnPath: .yarn/releases/yarn-3.0.2.cjs
