plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-miko.js
    spec: "@yarnpkg/plugin-miko"
  - path: .yarn/plugins/@yarnpkg/plugin-babel.js
    spec: "@yarnpkg/plugin-babel"
  - path: .yarn/plugins/@yarnpkg/plugin-builder.js
    spec: "@yarnpkg/plugin-builder"
  - path: .yarn/plugins/@yarnpkg/plugin-clean.js
    spec: "@yarnpkg/plugin-clean"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
