#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ "$(git branch --show-current)" = main ]; then
  sh $(dirname "$0")/build.sh
else
  sh $(dirname "$0")/build.sh "--since main"
fi

yarn miko husky post-checkout
